// W52 病房 Mock Data ── 41 床
// Status: "occupied" | "isolation" | "transfer" | "transfer-in" | "discharge" | "empty"
const MOCK_DATA = {
  HospitalInfo: {
    HospitalName: "高雄市立民生醫院",
    WardName: "W52病房",
    WardCode: "W52",
    WardDirector: "吳○明",
    HeadNurse: "林○芳"
  },
  Beds: [
    { BedId:"W52-001", Status:"occupied", Patient:{ PatientName:"林○志", Gender:"M", Age:75, AdmissionDate:"05/08", Diagnosis:"Hip fracture, Post-OP Day 3", AttendingDoctor:"張○醫師", PrimaryNurse:"陳○護理師", Condition:"穩定", Isolation:"無", Dnr:true, FallRisk:true, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:"輪椅", Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"A112345678", BirthDate:"1950/03/15", Department:"骨科", Notes:"" } },
    { BedId:"W52-003", Status:"occupied", Patient:{ PatientName:"黃○芬", Gender:"F", Age:68, AdmissionDate:"05/12", Diagnosis:"Osteoporosis with compression fracture L2", AttendingDoctor:"張○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:true, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:true, Consult:false, MedicalRecordNo:"B223456789", BirthDate:"1957/09/22", Department:"骨科", Notes:"對盤尼西林過敏" } },
    { BedId:"W52-006", Status:"isolation", Patient:{ PatientName:"王○豪", Gender:"M", Age:58, AdmissionDate:"05/10", Diagnosis:"Cellulitis, right lower limb, MRSA", AttendingDoctor:"李○醫師", PrimaryNurse:"鄭○護理師", Condition:"重症", Isolation:"接觸隔離", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:true, MedicalRecordNo:"C334567890", BirthDate:"1967/06/10", Department:"感染科", Notes:"接觸隔離，需穿戴手套與隔離衣" } },
    { BedId:"W52-008", Status:"occupied", Patient:{ PatientName:"陳○珠", Gender:"F", Age:56, AdmissionDate:"05/14", Diagnosis:"Appendectomy Post-OP Day 1", AttendingDoctor:"吳○醫師", PrimaryNurse:"陳○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:true, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:true, Exam:false, Consult:false, MedicalRecordNo:"D445678901", BirthDate:"1969/12/03", Department:"一般外科", Notes:"術後禁食，補充靜脈輸液" } },
    { BedId:"W52-010", Status:"occupied", Patient:{ PatientName:"蔡○文", Gender:"M", Age:71, AdmissionDate:"05/09", Diagnosis:"Benign prostatic hyperplasia, Post-TURP", AttendingDoctor:"許○醫師", PrimaryNurse:"林○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"E556789012", BirthDate:"1954/07/28", Department:"泌尿科", Notes:"" } },
    { BedId:"W52-012", Status:"occupied", Patient:{ PatientName:"謝○華", Gender:"F", Age:64, AdmissionDate:"05/11", Diagnosis:"Cholelithiasis, Laparoscopic cholecystectomy", AttendingDoctor:"吳○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:true, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:true, MedicalRecordNo:"F667890123", BirthDate:"1961/02/14", Department:"腸胃科", Notes:"" } },
    { BedId:"W52-015", Status:"occupied", Patient:{ PatientName:"洪○強", Gender:"M", Age:78, AdmissionDate:"05/07", Diagnosis:"COPD exacerbation", AttendingDoctor:"徐○醫師", PrimaryNurse:"林○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:true, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:true, Surgery:false, Exam:true, Consult:false, MedicalRecordNo:"G778901234", BirthDate:"1947/11/05", Department:"胸腔內科", Notes:"持續氧氣供應" } },
    { BedId:"W52-002", Status:"occupied", Patient:{ PatientName:"許○雯", Gender:"F", Age:45, AdmissionDate:"05/15", Diagnosis:"Uterine myomectomy, Post-OP Day 0", AttendingDoctor:"周○醫師", PrimaryNurse:"鄭○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:true, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:true, Exam:false, Consult:false, MedicalRecordNo:"H889012345", BirthDate:"1981/04/18", Department:"婦產科", Notes:"術後第一日，監測生命跡象" } },
    { BedId:"W52-005", Status:"occupied", Patient:{ PatientName:"彭○明", Gender:"M", Age:67, AdmissionDate:"05/10", Diagnosis:"Unstable angina, PCI completed", AttendingDoctor:"方○醫師", PrimaryNurse:"陳○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:true, CardiacCath:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"I990123456", BirthDate:"1958/08/30", Department:"心臟內科", Notes:"" } },
    { BedId:"W52-007", Status:"isolation", Patient:{ PatientName:"吳○美", Gender:"F", Age:83, AdmissionDate:"05/06", Diagnosis:"Influenza pneumonia", AttendingDoctor:"徐○醫師", PrimaryNurse:"林○護理師", Condition:"重症", Isolation:"飛沫隔離", Dnr:true, FallRisk:false, Dependency:"L2", Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:true, CVC:true, Foley:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"J001234567", BirthDate:"1942/01/20", Department:"胸腔內科", Notes:"飛沫隔離，需戴外科口罩" } },
    { BedId:"W52-009", Status:"occupied", Patient:{ PatientName:"楊○國", Gender:"M", Age:59, AdmissionDate:"05/13", Diagnosis:"Cerebral infarction, right hemiplegia", AttendingDoctor:"鄭○醫師", PrimaryNurse:"蔡○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:true, Dependency:"L3", Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:"推床", Oxygen:false, CVC:true, Foley:true, Surgery:false, Exam:true, Consult:false, MedicalRecordNo:"K112345679", BirthDate:"1966/10/07", Department:"神經內科", Notes:"" } },
    { BedId:"W52-011", Status:"transfer", Patient:{ PatientName:"林○川", Gender:"M", Age:73, AdmissionDate:"05/05", Diagnosis:"CKD Stage 4, AKI resolved", AttendingDoctor:"方○醫師", PrimaryNurse:"陳○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Renal:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"L223456790", BirthDate:"1952/05/19", Department:"腎臟科", Notes:"預計今日轉腎臟科病房" } },
    { BedId:"W52-013", Status:"discharge", Patient:{ PatientName:"周○玲", Gender:"F", Age:60, AdmissionDate:"05/09", Diagnosis:"T2DM with hyperglycemia, controlled", AttendingDoctor:"李○醫師", PrimaryNurse:"鄭○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"M334567891", BirthDate:"1965/03/08", Department:"內分泌科", Notes:"預計今日出院，衛教完成" } },
    { BedId:"W52-016", Status:"occupied", Patient:{ PatientName:"張○河", Gender:"M", Age:88, AdmissionDate:"05/01", Diagnosis:"CHF NYHA III, Atrial fibrillation", AttendingDoctor:"方○醫師", PrimaryNurse:"林○護理師", Condition:"重症", Isolation:"無", Dnr:true, FallRisk:true, Dependency:"L3", Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:"推床", Oxygen:true, CVC:true, Foley:true, Surgery:false, Exam:false, Consult:true, MedicalRecordNo:"N445678902", BirthDate:"1937/12/31", Department:"心臟內科", Notes:"需特別注意液體平衡" } },
    { BedId:"W52-017", Status:"occupied", Patient:{ PatientName:"蘇○婷", Gender:"F", Age:35, AdmissionDate:"05/14", Diagnosis:"Ectopic pregnancy, salpingectomy", AttendingDoctor:"周○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:true, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"O556789013", BirthDate:"1990/07/23", Department:"婦產科", Notes:"病人要求保密，不得透露住院資訊" } },
    { BedId:"W52-018", Status:"occupied", Patient:{ PatientName:"曾○宏", Gender:"M", Age:65, AdmissionDate:"05/11", Diagnosis:"Total knee replacement, Left, Post-OP Day 4", AttendingDoctor:"張○醫師", PrimaryNurse:"鄭○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:true, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:"輪椅", Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"P667890124", BirthDate:"1960/09/14", Department:"骨科", Notes:"" } },
    { BedId:"W52-019", Status:"occupied", Patient:{ PatientName:"賴○月", Gender:"F", Age:72, AdmissionDate:"05/08", Diagnosis:"Alzheimer's disease, UTI", AttendingDoctor:"鄭○醫師", PrimaryNurse:"林○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:true, Dependency:"L2", Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"Q778901235", BirthDate:"1953/04/06", Department:"老人醫學科", Notes:"認知障礙，需加護欄" } },
    { BedId:"W52-020", Status:"transfer-in", Patient:{ PatientName:"孫○華", Gender:"F", Age:69, AdmissionDate:"05/16", Diagnosis:"Pneumonia, discharged from ICU", AttendingDoctor:"徐○醫師", PrimaryNurse:"林○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"Z100200300", BirthDate:"1957/02/14", Department:"胸腔內科", Notes:"ICU 轉入，預計今日抵達" } },
    { BedId:"W52-021", Status:"occupied", Patient:{ PatientName:"鄭○樹", Gender:"M", Age:58, AdmissionDate:"05/12", Diagnosis:"Colorectal cancer, Post-Hemicolectomy Day 3", AttendingDoctor:"吳○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:true, MedicalRecordNo:"R889012346", BirthDate:"1967/11/29", Department:"大腸直腸外科", Notes:"" } },
    { BedId:"W52-022", Status:"occupied", Patient:{ PatientName:"黎○靜", Gender:"F", Age:52, AdmissionDate:"05/13", Diagnosis:"Gastric ulcer with bleeding, EGD hemostasis", AttendingDoctor:"謝○醫師", PrimaryNurse:"陳○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:true, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:true, Consult:false, MedicalRecordNo:"S990123457", BirthDate:"1973/02/11", Department:"腸胃科", Notes:"" } },
    { BedId:"W52-023", Status:"occupied", Patient:{ PatientName:"許○仁", Gender:"M", Age:77, AdmissionDate:"05/09", Diagnosis:"COPD, Pneumonia, right lower lobe", AttendingDoctor:"徐○醫師", PrimaryNurse:"林○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:true, Rrt:false, Chemo:false, Transport:null, Oxygen:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"T001234568", BirthDate:"1948/06/17", Department:"胸腔內科", Notes:"" } },
    { BedId:"W52-025", Status:"occupied", Patient:{ PatientName:"江○如", Gender:"F", Age:51, AdmissionDate:"05/14", Diagnosis:"Mastectomy, Left, Post-OP Day 1", AttendingDoctor:"柯○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:true, Exam:false, Consult:false, MedicalRecordNo:"U112345679", BirthDate:"1974/08/24", Department:"乳房外科", Notes:"" } },
    { BedId:"W52-026", Status:"isolation", Patient:{ PatientName:"馬○德", Gender:"M", Age:84, AdmissionDate:"05/07", Diagnosis:"Pulmonary tuberculosis, active", AttendingDoctor:"徐○醫師", PrimaryNurse:"鄭○護理師", Condition:"重症", Isolation:"空氣隔離", Dnr:false, FallRisk:false, Dependency:"L2", Confidential:false, NoTreatment:true, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:true, Foley:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"V223456790", BirthDate:"1941/03/02", Department:"胸腔內科", Notes:"空氣隔離，需佩戴N95口罩" } },
    { BedId:"W52-027", Status:"occupied", Patient:{ PatientName:"朱○玉", Gender:"F", Age:55, AdmissionDate:"05/10", Diagnosis:"Breast cancer Stage III, 2nd cycle chemo", AttendingDoctor:"柯○醫師", PrimaryNurse:"陳○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:true, Allergy:true, Rrt:false, Chemo:true, Transport:null, Oxygen:false, PortCath:true, Foley:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"W334567891", BirthDate:"1970/10/16", Department:"腫瘤科", Notes:"化療中，注意骨髓抑制" } },
    { BedId:"W52-028", Status:"occupied", Patient:{ PatientName:"施○平", Gender:"M", Age:70, AdmissionDate:"05/12", Diagnosis:"Coronary artery disease, CABG Post-OP Day 3", AttendingDoctor:"方○醫師", PrimaryNurse:"林○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, CVC:true, Foley:true, Surgery:true, Exam:false, Consult:false, MedicalRecordNo:"X445678902", BirthDate:"1955/01/09", Department:"心臟外科", Notes:"" } },
    { BedId:"W52-029", Status:"occupied", Patient:{ PatientName:"莊○真", Gender:"F", Age:66, AdmissionDate:"05/11", Diagnosis:"Femur fracture, ORIF Post-OP Day 4", AttendingDoctor:"張○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:true, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:"輪椅", Oxygen:false, Surgery:false, Exam:true, Consult:false, MedicalRecordNo:"Y556789013", BirthDate:"1959/07/12", Department:"骨科", Notes:"" } },
    { BedId:"W52-030", Status:"empty", Patient:null },
    { BedId:"W52-031", Status:"occupied", Patient:{ PatientName:"羅○凱", Gender:"M", Age:53, AdmissionDate:"05/13", Diagnosis:"Subarachnoid hemorrhage, Grade II", AttendingDoctor:"鄭○醫師", PrimaryNurse:"陳○護理師", Condition:"危急", Isolation:"無", Dnr:false, FallRisk:true, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:true, Chemo:false, Transport:null, Oxygen:true, CVC:true, Foley:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"Z667890124", BirthDate:"1972/05/25", Department:"神經外科", Notes:"RRT 啟動，密切監測" } },
    { BedId:"W52-032", Status:"occupied", Patient:{ PatientName:"洪○玲", Gender:"F", Age:79, AdmissionDate:"05/08", Diagnosis:"Nephrotic syndrome, CKD Stage 3", AttendingDoctor:"方○醫師", PrimaryNurse:"林○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Renal:true, Surgery:false, Exam:true, Consult:false, MedicalRecordNo:"A778901235", BirthDate:"1946/02/03", Department:"腎臟科", Notes:"" } },
    { BedId:"W52-033", Status:"transfer", Patient:{ PatientName:"游○福", Gender:"M", Age:63, AdmissionDate:"05/06", Diagnosis:"Ileus, Conservative treatment completed", AttendingDoctor:"吳○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"B889012346", BirthDate:"1962/09/01", Department:"一般外科", Notes:"預計轉外科觀察病房" } },
    { BedId:"W52-035", Status:"occupied", Patient:{ PatientName:"鄒○雲", Gender:"F", Age:87, AdmissionDate:"05/03", Diagnosis:"Dementia, Aspiration pneumonia", AttendingDoctor:"鄭○醫師", PrimaryNurse:"鄭○護理師", Condition:"重症", Isolation:"無", Dnr:true, FallRisk:false, Dependency:"L3", Confidential:false, NoTreatment:false, Npo:true, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Foley:true, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"C990123457", BirthDate:"1938/11/14", Department:"老人醫學科", Notes:"管灌餵食中" } },
    { BedId:"W52-036", Status:"occupied", Patient:{ PatientName:"戴○昌", Gender:"M", Age:48, AdmissionDate:"05/15", Diagnosis:"ACL reconstruction, Post-OP Day 0", AttendingDoctor:"張○醫師", PrimaryNurse:"陳○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:true, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:true, Exam:false, Consult:false, MedicalRecordNo:"D001234568", BirthDate:"1978/03/20", Department:"骨科", Notes:"" } },
    { BedId:"W52-037", Status:"occupied", Patient:{ PatientName:"葉○秀", Gender:"F", Age:71, AdmissionDate:"05/10", Diagnosis:"Hypertension with heart failure", AttendingDoctor:"方○醫師", PrimaryNurse:"林○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:true, Consult:false, MedicalRecordNo:"E112345679", BirthDate:"1954/08/27", Department:"心臟內科", Notes:"" } },
    { BedId:"W52-038", Status:"isolation", Patient:{ PatientName:"梁○山", Gender:"M", Age:80, AdmissionDate:"05/09", Diagnosis:"Urinary tract infection, MDR-organism", AttendingDoctor:"許○醫師", PrimaryNurse:"蔡○護理師", Condition:"重症", Isolation:"接觸隔離", Dnr:false, FallRisk:true, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:true, MedicalRecordNo:"F223456790", BirthDate:"1945/06/06", Department:"泌尿科", Notes:"接觸隔離，廣泛抗藥性菌種" } },
    { BedId:"W52-039", Status:"occupied", Patient:{ PatientName:"莫○英", Gender:"F", Age:55, AdmissionDate:"05/12", Diagnosis:"Thyroidectomy, total, Post-OP Day 3", AttendingDoctor:"李○醫師", PrimaryNurse:"鄭○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:true, MedicalRecordNo:"G334567891", BirthDate:"1970/01/30", Department:"一般外科", Notes:"注意低血鈣症狀" } },
    { BedId:"W52-050", Status:"occupied", Patient:{ PatientName:"費○達", Gender:"M", Age:76, AdmissionDate:"05/11", Diagnosis:"Aortic valve replacement, Post-OP Day 4", AttendingDoctor:"方○醫師", PrimaryNurse:"陳○護理師", Condition:"重症", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:true, CVC:true, Foley:true, Surgery:true, Exam:false, Consult:false, MedicalRecordNo:"H445678902", BirthDate:"1949/04/13", Department:"心臟外科", Notes:"" } },
    { BedId:"W52-051", Status:"occupied", Patient:{ PatientName:"魏○珍", Gender:"F", Age:61, AdmissionDate:"05/13", Diagnosis:"Gastroesophageal reflux, Fundoplication", AttendingDoctor:"謝○醫師", PrimaryNurse:"林○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"I556789013", BirthDate:"1964/12/08", Department:"腸胃科", Notes:"" } },
    { BedId:"W52-052", Status:"occupied", Patient:{ PatientName:"龔○德", Gender:"M", Age:68, AdmissionDate:"05/08", Diagnosis:"Lumbar disc herniation, L4-5, microdiscectomy", AttendingDoctor:"鄭○醫師", PrimaryNurse:"蔡○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:true, Dependency:null, Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:false, MedicalRecordNo:"J667890124", BirthDate:"1957/06/22", Department:"神經外科", Notes:"" } },
    { BedId:"W52-053", Status:"occupied", Patient:{ PatientName:"易○桂", Gender:"F", Age:73, AdmissionDate:"05/06", Diagnosis:"Parkinson's disease, aspiration pneumonia", AttendingDoctor:"鄭○醫師", PrimaryNurse:"鄭○護理師", Condition:"重症", Isolation:"無", Dnr:true, FallRisk:false, Dependency:"L2", Confidential:false, NoTreatment:false, Npo:false, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:false, Exam:false, Consult:true, MedicalRecordNo:"K778901235", BirthDate:"1952/09/17", Department:"神經內科", Notes:"" } },
    { BedId:"W52-055", Status:"occupied", Patient:{ PatientName:"白○成", Gender:"M", Age:62, AdmissionDate:"05/15", Diagnosis:"Gastric cancer, Post-Distal gastrectomy Day 2", AttendingDoctor:"吳○醫師", PrimaryNurse:"陳○護理師", Condition:"穩定", Isolation:"無", Dnr:false, FallRisk:false, Dependency:null, Confidential:false, NoTreatment:false, Npo:true, Allergy:false, Rrt:false, Chemo:false, Transport:null, Oxygen:false, Surgery:true, Exam:false, Consult:false, MedicalRecordNo:"L889012346", BirthDate:"1963/07/04", Department:"一般外科", Notes:"術後禁食，NG 管灌注中" } },
    { BedId:"W52-056", Status:"empty", Patient:null }
  ]
}

export function getStats(beds) {
  return {
    total:     beds.length,
    occupied:  beds.filter(b => b.Status !== 'empty').length,
    surgery:   beds.filter(b => b.Patient?.Surgery).length,
    exam:      beds.filter(b => b.Patient?.Exam).length,
    consult:   beds.filter(b => b.Patient?.Consult).length,
    isolation: beds.filter(b => b.Status === 'isolation').length,
    dnr:       beds.filter(b => b.Patient?.Dnr).length,
    rrt:       beds.filter(b => b.Patient?.Rrt).length,
    port:      beds.filter(b => b.Patient?.PortCath).length,
    dlvc:      beds.filter(b => b.Patient?.DLVC).length,
    foley:     beds.filter(b => b.Patient?.Foley).length,
    cvc:       beds.filter(b => b.Patient?.CVC).length,
    cardiac:   beds.filter(b => b.Patient?.CardiacCath).length,
  }
}

export default MOCK_DATA
